import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/lib/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    'bg-slate-950',
    'bg-slate-900',
    'bg-slate-800',
    'bg-zinc-950',
    'bg-zinc-900',
    'bg-blue-950',
    'bg-blue-900',
    'bg-orange-950',
    'bg-orange-900',
    'bg-gray-950',
    'bg-gray-900',
    'bg-black',
    'bg-navy',
    'border-blue-900/40',
    'border-blue-900/50',
    'border-blue-900/60',
    'border-blue-800/40',
    'border-blue-800/50',
    'border-blue-800/60',
    'border-teal-900/40',
    'border-teal-900/50',
    'border-teal-900/60',
    'border-cyan-900/40',
    'border-cyan-900/50',
    'border-cyan-900/60',
    'border-cyan-800/40',
    'border-cyan-800/50',
    'border-cyan-800/60',
    'border-emerald-900/40',
    'border-emerald-900/50',
    'border-emerald-900/60',
    'border-emerald-950/60',
    'border-emerald-800/40',
    'border-indigo-900/40',
    'border-indigo-800/40',
    'border-indigo-800/50',
    'border-indigo-800/60',
    'border-orange-950/50',
    'border-orange-900/50',
    'border-orange-900/60',
    'border-orange-800/40',
    'border-orange-800/50',
    'border-orange-800/70',
    'border-slate-800',
    'border-slate-700',
    'border-emerald-500/40',
    'border-cyan-400/40',
    'hover:text-teal-400',
    'hover:text-teal-300',
    'hover:text-cyan-400',
    'hover:text-cyan-300',
    'hover:text-emerald-400',
    'hover:text-emerald-300',
    'hover:text-blue-400',
    'hover:text-orange-400',
    'hover:text-orange-300',
    'hover:text-indigo-400',
    'hover:text-indigo-300',
    'bg-teal-500',
    'bg-cyan-500',
    'bg-emerald-500',
    'bg-orange-500',
    'bg-blue-500',
    'bg-indigo-500',
  ],
  theme: {
    extend: {
      colors: {
        'navy': '#0F172A',
        'dark-blue': '#1E3A8A',
        'teal': '#14B8A6',
        'cyan': '#06B6D4',
        'gold': '#F59E0B',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['Plus Jakarta Sans', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
      },
      backgroundImage: {
        'gradient-navy': 'linear-gradient(135deg, #0F172A 0%, #1E3A8A 100%)',
        'gradient-accent': 'linear-gradient(135deg, #14B8A6 0%, #06B6D4 100%)',
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'slide-in': 'slide-in 0.5s ease-out',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        'slide-in': {
          '0%': { transform: 'translateX(-100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
      },
      typography: {
        DEFAULT: {
          css: {
            maxWidth: '100%',
            img: {
              maxWidth: '100%',
              height: 'auto',
            },
            table: {
              overflowX: 'auto',
            },
            pre: {
              overflowX: 'auto',
              maxWidth: '100%',
            },
          },
        },
      },
    },
  },
  plugins: [],
}

export default config
